[colors.bright]
black = "0x444b6a"
blue = "0x7da6ff"
cyan = "0x0db9d7"
green = "0xb9f27c"
magenta = "0xbb9af7"
red = "0xff7a93"
white = "0xacb0d0"
yellow = "0xff9e64"

[colors.normal]
black = "0x32344a"
blue = "0x81a1c1"
cyan = "0x7aa2f7"
green = "0x9ece6a"
magenta = "0xad8ee6"
red = "0xf7768e"
white = "0xe5e9f0"
yellow = "0xebcb8c"

[colors.primary]
background = "0x1a1b26"
foreground = "0xe5e9f0"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Extra Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Extra Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
dynamic_padding = true
