env:
  TERM: xterm-256color

schemes:
  tokyo-night: &tokyo-night
    primary:
      background: '0x1a1b26'
      foreground: '0xe5e9f0'

    normal:
      black:   '0x32344a'
      red:     '0xf7768e'
      green:   '0x9ece6a'
      yellow:  '0xebcb8c'
      blue:    '0x81a1c1'
      magenta: '0xad8ee6'
      cyan:    '0x7aa2f7'
      white:   '0xe5e9f0'

    bright:
      black:   '0x444b6a'
      red:     '0xff7a93'
      green:   '0xb9f27c'
      yellow:  '0xff9e64'
      blue:    '0x7da6ff'
      magenta: '0xbb9af7'
      cyan:    '0x0db9d7'
      white:   '0xacb0d0'

colors: *tokyo-night

font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular

  bold:
    family: JetBrainsMono Nerd Font
    style: Extra Bold

  italic:
    family: JetBrainsMono Nerd Font
    style: Medium Italic

  bold_italic:
    family: JetBrainsMono Nerd Font
    style: Extra Bold Italic

  size: 7.5

window:
  dynamic_padding: true
  #padding:
    #x: 8
    #y: 8
