source $HOME/.config/nvim/keys/mappings.vim
source $HOME/.config/nvim/colors/tokyonight.lua
source $HOME/.config/nvim/config/plug-colorizer.lua
source $HOME/.config/nvim/config/nvim-tree-config.lua
source $HOME/.config/nvim/config/lsp.lua
source $HOME/.config/nvim/config/lualine-config.lua
source $HOME/.config/nvim/config/bufferline-config.lua
source $HOME/.config/nvim/config/treesitter-config.lua
source $HOME/.config/nvim/config/telescope.lua
source $HOME/.config/nvim/config/gitsigns.lua
