require("options")
require("plugins")
require("keymaps")

-- Plugins
require("config.colorscheme")
require("config.nvim-tree")
require("config.bufferline")
require("config.lualine")
require("config.gitsigns")
require("config.autopairs")
require("config.telescope")
require("config.toggleterm")
require("config.treesitter")
require("config.coc")
